'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8800
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace cfdistatus
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Acuse", [Namespace]:="http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Acuse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoEstatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EsCancelableField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstatusCancelacionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoEstatus() As String
            Get
                Return Me.CodigoEstatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoEstatusField, value) <> true) Then
                    Me.CodigoEstatusField = value
                    Me.RaisePropertyChanged("CodigoEstatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EsCancelable() As String
            Get
                Return Me.EsCancelableField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EsCancelableField, value) <> true) Then
                    Me.EsCancelableField = value
                    Me.RaisePropertyChanged("EsCancelable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estado() As String
            Get
                Return Me.EstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoField, value) <> true) Then
                    Me.EstadoField = value
                    Me.RaisePropertyChanged("Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstatusCancelacion() As String
            Get
                Return Me.EstatusCancelacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstatusCancelacionField, value) <> true) Then
                    Me.EstatusCancelacionField = value
                    Me.RaisePropertyChanged("EstatusCancelacion")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="cfdistatus.IConsultaCFDIService")>  _
    Public Interface IConsultaCFDIService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IConsultaCFDIService/Consulta", ReplyAction:="http://tempuri.org/IConsultaCFDIService/ConsultaResponse")>  _
        Function Consulta(ByVal expresionImpresa As String) As cfdistatus.Acuse
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IConsultaCFDIServiceChannel
        Inherits cfdistatus.IConsultaCFDIService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ConsultaCFDIServiceClient
        Inherits System.ServiceModel.ClientBase(Of cfdistatus.IConsultaCFDIService)
        Implements cfdistatus.IConsultaCFDIService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Consulta(ByVal expresionImpresa As String) As cfdistatus.Acuse Implements cfdistatus.IConsultaCFDIService.Consulta
            Return MyBase.Channel.Consulta(expresionImpresa)
        End Function
    End Class
End Namespace
